version: '3'

services:
  sharebook_db:
    image: postgres:11.2-alpine
    container_name: sharebook_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=share_book